### ISSUE TITLE
the 'dns' and 'domain' options only applied to DHCPv6, and not to RAs.

### ISSUE THREAD

**Issue by dsanke** [cshoredaniel/lede-odhcpd#1]
the 'dns' and 'domain' options only applied to DHCPv6, and not to RAs.
Android devices cannot get corrent DNS via SLAAC.

**Comment by cshoredaniel** [comment]
Sorry this was just a copy of LEDE's odhcpd repo.  I've stopped working on OpenWrt/LEDE so this is now irrelevant.
